const ACTION_TYPES = {
    ADD_NEW_CONTACT: 'ADD_NEW_CONTACT',
    POST_NEW_CONTACT:'POST_NEW_CONTACT',
    PUT_CONTACT: 'PUT_CONTACT',
    DELETE_CONTACT: 'DELETE_CONTACT',
    SELECT_CONTACT: 'SELECT_CONTACT',
    GET_CONTACTS: 'GET_CONTACTS',
}

export default ACTION_TYPES